stages:
  - build_and_test
image: ubuntu:24.04
build_source_and_test: # test should be done in a system container, but docker is not the one.
  stage: build_and_test
  script:
    - apt-get update
    - apt-get install -y git
    - git clone https://gitlab.yoonjin2.kr/yjlee/linuxVirtualization
    - cd incuspeed
    - git submodule init
    - git submodule update --recursive # to handle further changes
    - bash ./initial_setup.sh
    - chmod +x incuspeedServer # just check if the file can get execute permission
      # if this failes, file is not present

