stages:
  - build_and_test
image: ubuntu:24.04
build_source:
  stage: build_and_test
  script:
    - apt-get update
    - apt-get install -y git
    - git clone https://gitlab.yoonjin2.kr/yjlee/linuxVirtualization
    - cd linuxVirtualization
    - git submodule init
    - git submodule update --recursive # to handle further changes
    - bash ./initial_setup.sh
    - ./linuxVirtualizationServer

