#!/bin/bash

# CA Information
CA_CN="hobbies.yoonjin2.kr"
CA_DAYS=3650
CA_KEY_FILE="ca.key"
CA_CERT_FILE="ca.crt"

# Server Information
SERVER_CN="hobbies.yoonjin2.kr"
SERVER_DAYS=365
SERVER_KEY_FILE="server.key"
SERVER_CSR_FILE="server.csr"
SERVER_CERT_FILE="server.crt"

# OpenSSL Configuration
OPENSSL_CNF="./openssl.cnf"

# 1. Generate CA Private Key
echo "Generating CA private key..."
openssl genrsa -out "$CA_KEY_FILE" 2048

# 2. Generate CA Certificate (Self-Signed)
echo "Generating CA certificate..."
openssl req -x509 -new -nodes -key "$CA_KEY_FILE" \
  -subj "/C=KR/ST=Gyeongsangbuk-do/L=Gyeongsan-si/O=LVirt Project/CN=$CA_CN" \
  -days "$CA_DAYS" -out "$CA_CERT_FILE" -config "$OPENSSL_CNF" -extensions v3_ca

# 3. Generate Server Private Key
echo "Generating server private key..."
openssl genrsa -out "$SERVER_KEY_FILE" 2048

# 4. Generate Server CSR
echo "Generating server certificate signing request..."
openssl req -new -key "$SERVER_KEY_FILE" \
  -subj "/C=KR/ST=Gyeongsangbuk-do/L=Gyeongsan-si/O=LVirt Project/CN=$SERVER_CN" \
  -out "$SERVER_CSR_FILE" -config "$OPENSSL_CNF"

# 5. Sign Server Certificate with CA
echo "Signing server certificate with CA..."
openssl x509 -req -in "$SERVER_CSR_FILE" -CA "$CA_CERT_FILE" -CAkey "$CA_KEY_FILE" \
  -CAcreateserial -out "$SERVER_CERT_FILE" -days "$SERVER_DAYS" -sha256 \
  -extfile "$OPENSSL_CNF" -extensions v3_server

# Move certs
mkdir -p certs app/certs
mv server.crt certs/
mv server.key certs/
mv ca.crt app/certs/

echo "Certificates generated successfully."

#Auto Generated By ChatGPT
