name: Run Script with Root Privileges (Go) on Ubuntu 24.04 LTS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.23.0'

    - name: Make script executable
      run: chmod +x ./initial_setup.sh

    - name: Run script with root privileges
      run: sudo ./initial_setup.sh
